# Generated by Django 3.2 on 2021-10-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='questions',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='topic',
        ),
    ]
