# Generated by Django 3.2 on 2021-10-04 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_auto_20211004_0643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='char_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='text_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='text_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='fk_answered',
            new_name='answered_by',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='char_header',
            new_name='header',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='text_question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='fk_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='fk_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='text_topic',
            new_name='description',
        ),
    ]
