# Generated by Django 3.2 on 2021-10-04 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('char_code', models.CharField(blank=True, max_length=200, null=True)),
                ('char_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_created_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_created_by', to=settings.AUTH_USER_MODEL)),
                ('fk_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('char_code', models.CharField(blank=True, max_length=200, null=True)),
                ('char_name', models.CharField(blank=True, max_length=200, null=True)),
                ('fk_created_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
                ('fk_modified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_modified_by', to=settings.AUTH_USER_MODEL)),
                ('fk_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
