# Generated by Django 3.2 on 2021-10-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
    ]
