# Generated by Django 3.2 on 2021-10-04 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20211004_0728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='modified_at',
            new_name='modified_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='created_at',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='modified_at',
            new_name='modified_date',
        ),
    ]
