# Generated by Django 3.2 on 2021-10-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211004_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='int_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
